services:
  simple-web-service:
    build: .
    volumes:
      - ./text.log:/usr/src/app/text.log
    container_name: simple-web-service
    command: ["server"]
    ports:
      - "127.0.0.1:8080:8080"
