services:
  example-backend:
    build: ./backend/
    container_name: example-backend
    environment:
      - REDIS_HOST=redis
      - POSTGRES_PASSWORD=exercises2-9
      - POSTGRES_HOST=db
    ports:
      - "127.0.0.1:8080:8080"
  example-frontend:
    build: ./frontend/
    container_name: example-frontend
    ports:
      - "127.0.0.1:5000:5000"
  redis:
    image: redis:7.2.5-alpine3.19
    container_name: redis
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_PASSWORD=exercises2-9
    container_name: exercises2-9_db
    volumes:
      - ./database:/var/lib/postgresql/data
  nginx:
    image: nginx:1.25.5-alpine3.19
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 127.0.0.1:80:80
    depends_on:
      - example-frontend
      - example-backend
