services:
  example-backend:
    image: example-backend
    build: ./backend/
    container_name: example-backend
    ports:
      - 8080:8080
  example-frontend:
    image: example-frontend
    build: ./frontend/
    container_name: example-frontend
    ports:
      - 5000:5000
