FROM python:3.12-alpine

WORKDIR /mydir

RUN apk add --no-cache curl ca-certificates && \
    curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp && \
    apk del curl && \
    chmod a+x /usr/local/bin/yt-dlp && \
    adduser -D appuser && \
    chown appuser .

USER appuser

ENTRYPOINT [ "/usr/local/bin/yt-dlp" ]